### ISSUE TITLE
"undefined" message after open new ticket

### ISSUE THREAD

**Issue by qwertyhq0x** [bostrot/telegram-support-bot#143]
When a user opens a new ticket or writes the first message to the bot) they receive a message from the bot with the text: undefined If ticket number display is enabled: undefinedTicket #T000020
![Снимок экрана 2023-04-20 123527](https://user-images.githubusercontent.com/83676869/233324946-c3ec5248-55aa-421a-ad5a-63295ca2e337.png)
![Снимок экрана 2023-04-20 123601](https://user-images.githubusercontent.com/83676869/233325020-091c91fe-7fd4-414e-b547-47eec10c93d8.png)

how to fix it? 

There's also another bug, I don't know what it's connected to, it doesn't send automatic messages This is what it says in debug:

```
Thu Apr 20 2023 09:58:08 GMT+0000 (Coordinated Universal Time): === UNHANDLED REJECTION ===
GrammyError: Call to 'sendMessage' failed! (400: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 107)
```

I am using Russian lenguage, is it possible that the code cannot handle it?

**Comment by bostrot** [comment]
It can handle it. Can you share your `config.yaml` (replace the bot token before sharing)?

**Comment by FeliksMarello** [comment]
Good afternoon, I'm facing exactly the same problem, how can I fix it?

**Comment by FeliksMarello** [comment]
```
# -*- coding: utf-8 -*-
# bot settings
bot_token: '' # support bot token
staffchat_id: '' # eg. -123456789
owner_id: ''
spam_time: 300000 # time (in MS) in which user may send 5 messages
spam_cant_msg: 5

parse_mode: 'Markdown' # Experimental. Do not change unless you know what you are doing. Options: Markdown/MarkdownV2/HTML

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private
auto_close_tickets: false # Close tickets after answering
anonymous_tickets: false # Include userid in tickets or not
anonymous_replies: true # Include staff member name in response
show_auto_replied: true # Send auto replied msgs to staff chat
show_user_ticket: true # Show ticket id to user
autoreply_confirmation: true # Reply with language.confirmationMessage on each incoming message
clean_replies: false # Remove footer and header from response
pass_start: true # Pass /start command to support directly

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# настройте свой язык
language:
  startCommandText: 'Добро пожаловать в наш чат поддержки! Задайте свой вопрос здесь.'
  faqCommandText: ''
  helpCommandText: "*Доступные команды:* /help /faq /id"
  helpCommandStaffText: "*Доступные команды:*\n
    /start - Немного введения \n
    /faq - Показать часто задаваемые вопросы \n
    /open - *Сотрудник* Показывает список открытых тикетов \n
    /reopen - *Сотрудник* Переоткрывает закрытый тикет \n
    /close - *Сотрудник* Ответьте на тикет с этим, чтобы закрыть и разблокировать \n
    /clear - *Сотрудник* Закрывает все тикеты \n
    /ban - *Сотрудник* Забанить пользователя в чате \n
    /unban - *Сотрудник* Разблокировать пользователя"
  confirmationMessage: "Спасибо за обращение к нам. Мы ответим вам как можно скорее."
  blockedSpam: "Вы отправили довольно много вопросов за последнее время. Пожалуйста, успокойтесь и дождитесь, пока персонал их проверит."
  ticket: 'Тикет'
  closed: 'Закрыт'
  acceptedBy: 'Был принят'
  dear: 'Привет'
  regards: 'С уважением,'
  from: 'От'
  language: 'Язык'
  msg_sent: 'Сообщение отправлено пользователю'
  file_sent: 'Файл отправлен пользователю'
  usr_with_ticket: 'Пользователь с тикетом'
  banned: 'Забанен'
  replyPrivate: 'Ответить в привате'
  services: 'Выберите сервис из списка ниже'
  customer: 'Клиент'
  msgForwarding: 'Ваши сообщения теперь будут пересылаться поставщикам группы: '
  back: 'Назад'
  whatSubCategory: 'Какая подкатегория лучше всего описывает ваши потребности?'
  prvChatEnded: 'Приватный чат закончился.'
  prvChatOpened: 'Открыт приватный чат с клиентом.'
  prvChatEnd: 'Закончить приватный чат'
  prvChatOpenedCustomer: 'Открыт приватный чат'
  instructionsSent: 'Инструкции были отправлены вам в приватном чате.'
  openTickets: 'Открытые тикеты'
  support: 'Поддержка'
  prvChatOnly: 'Эта команда может использоваться только в чате.'
  ticketClosed: 'Ваш тикет был закрыт нашим персоналом. Вы можете открыть новый тикет в любое время.'
  links: 'Прямые ссылки на поддержку'
  textFirst: 'Пожалуйста, отправьте нам сообщение перед отправкой изображения, чтобы мы могли вам лучше помочь.'
  ticketClosedError: 'Вы не можете ответить на закрытый тикет.'
  automatedReply: 'Это автоматический ответ.'
  automatedReplyAuthor: 'HQ_BOTs'
  doesntHelp: 'Это не помогает.'
  automatedReplySent: 'Автоматический ответ был отправлен пользователю.'
  ticketReopened: 'Тикет был переоткрыт.'
  regardsGroup: 'Ваш HQ VPN'



autoreply:
  - question: 'install'
    answer: ""
  - question: 'are you sure?'
    answer: 'Yes.'
# categories:
#  - name: "Проблема с подключением"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Проблема с Ключами"
#    subgroups:
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Создать Новый Т"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910"
#  - name: "Other issues"
#    tag: "#other"
#    msg: "Please specify your order number and describe the problem in as much detail as possible"
#    group_id: "-12345678910"
#  - name: "Contact"
#    msg: "Check out our Website"
```
